import { Metadata } from "next"
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
    title: 'Simple Social',
    description: 'Generated by create next app',
}

export default async function AuthLayout({ children }: { children: React.ReactNode }) {
    const session = await getServerSession();

    if(session) return redirect('/');

    return <>{children}</>
}