import { AsideMenu } from "@/components/aside-menu";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Simple Social | Main',
  description: 'Generated by create next app',
}

export default function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex">
        <AsideMenu/>
        <main className='flex flex-col flex-1 p-6 overflow-auto max-h-screen'>
            {children}
        </main>
    </div>
  )
}
