import { NewPost } from "@/components/new-post/new-post";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'Simple Social | Feed',
    description: 'Generated by create next app',
}

export default function FeedLayout({ children }: { children: React.ReactNode }) {
    return (
        <>
            <NewPost />
            {children}
        </>
    )
}
