import { nextAuthOptions } from "@/app/api/auth/[...nextauth]/route";
import { SessionUserCard } from "@/components/session-user-card/session-user-card";
import { getServerSession } from "next-auth";
import { IUsuario } from "@/models/usuario";
import { Metadata } from "next";
import { Post } from "@/components/post/post";

export const metadata: Metadata = {
  title: 'Simple Social | My Profile',
  description: 'Generated by create next app',
}

export default async function My() {
  const session = await getServerSession(nextAuthOptions);

  return (
    <>
      <SessionUserCard user={session?.user as IUsuario}/>
      <ul className="flex flex-col items-center gap-8">
        {session?.user?.posts?.map((post, i) => (
          <li key={i}>
            <Post
              post={{...post, user: session?.user as IUsuario}}
              user={session.user as IUsuario}
            />
          </li>
        ))}
      </ul>
    </>
  )
}