
import { PremiumCard } from "@/components/premium-card";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Simple Social | Time Line',
  description: 'Generated by create next app',
}

export default function TimelineLayout({ children }: { children: React.ReactNode }) {
  return (
      <div className='flex gap-6'>
        <main className='flex-1 overflow-hidden space-y-8'>
          {children}
        </main>
        <div className='h-fit'>
          <PremiumCard />
        </div>
      </div>
  )
}
